name: CI # имя пайплайна в Actions

on: # когда запускать
  push: # при пушах
    branches: [main]
  pull_request: # при PR
  workflow_dispatch: {} # можно запустить руками кнопкой “Run workflow”

jobs:
  build_and_test: # имя job (набор шагов)
    runs-on: ubuntu-latest # агент – Ubuntu
    steps: # шаги, выполняемые по порядку
      - uses: actions/checkout@v4 # вытащить код из твоего репо
      - uses: actions/setup-node@v4 # поставить Node
        with:
          node-version: 18
          cache: npm
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Build (CI mode)
        run: npm run build:ci # сборка (чистые логи)
      - name: Test (CI mode)
        run: npm run test:ci # тесты (подробные логи)
