name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: {} # даст кнопку "Run workflow" руками

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build (CI mode)
        run: npm run build:ci

      - name: Test (CI mode)
        run: npm run test:ci
